### ISSUE TITLE
subtomogram alignment protocol does not store the transformation matrix

### ISSUE THREAD

**Issue by Vilax** [scipion-em/scipion-em-emantomo#100]
When a set of subtomograms are aligned with emantomo, the alignment is not stored in the sqlite.

To reproduce this behaviour you can follow the next steps:

A set of subtomograms are aligned with emantomo. The aligned subtomograms are averaged and this average should consider the previous alignment 

1) If the average is done with dynamo or relion, the average is a ball of noise
2) When the average is carried out with emantomo, the average looks like the protein (ribosome).

Emantomo seems to work with hdf and the information is stored in the hdf. Eman works with hdf, but relion or dynamo do not. This is my hunch.

Eman refinement
![image](https://github.com/scipion-em/scipion-em-emantomo/assets/12271438/e6129563-0ddf-4fc2-a164-91681957ef9e)

Relion or dynamo average
![image](https://github.com/scipion-em/scipion-em-emantomo/assets/12271438/3485dc2e-9d3c-45bf-971b-beb3b077a5e7)

Eman average
![image](https://github.com/scipion-em/scipion-em-emantomo/assets/12271438/ebaa1c31-468c-4a5b-a9c9-2b8f573b3219)

**Comment by JorMaister** [comment]
@Vilax , I suppose it's not the pppt approach, but the classic one. Am I right?

**Comment by Vilax** [comment]
Correct, it is the classic subtomogram approach

**Comment by JorMaister** [comment]
Thanks, @Vilax. We've found and fix something similar in the pppt approach, so it may be similar. I'll let you know when it's fixed.
