### ISSUE TITLE
If template matching does not find anything, throw an exception

### ISSUE THREAD

**Issue by JorMaister** [scipion-em/scipion-em-emantomo#103]

**Comment by pconesa** [comment]
From @rdrighetto:

emantomo - template matching not giving any output? 
Already reported on Discord

**Comment by JorMaister** [comment]
Hi, @rdrighetto,
I haven't been able to reproduce it. Could you execute the the emantomo template matching tests and check if the output is correctly generated? The command to be executed is:

scipion3 tests emantomo.tests.test_protocols_sta_classic_workflow.TestEmanTemplateMatchingStaClassic

**Comment by rdrighetto** [comment]
Hi Jorge,

Thanks for looking into it. In the test it worked fine, returning 100
particles. I will double check what was doing when trying on my data.

--
Ricardo Diogo Righetto


Em ter., 5 de mar. de 2024 às 10:27, Jorge Jiménez de la Morena <
***@***.***> escreveu:

**Comment by Vilax** [comment]
I was able to reproduce the issue in alter machine. You can see a screenshot here

![image](https://github.com/scipion-em/scipion-em-emantomo/assets/12271438/ef177e00-c2e4-4b9e-b016-ee3590179ec2)

**Comment by JorMaister** [comment]
Thanks, @Vilax,

I'll check that project in Alter
