### ISSUE TITLE
double unserscore in filename makes emanpicker, and probably any eman method fail

### ISSUE THREAD

**Issue by pconesa** [scipion-em/scipion-em-emantomo#115]

**Comment by JorMaister** [comment]
Hi, everyone I seem to be having issues with the eman manual picking protocol.

1.  The tomogram window that pops up does not update with the number of particles I pick and remains "to do" even if I have picked those tomograms.

2. If I close the windows and click on continue all of the tomograms are listed as done with the number of particles I picked before being present in all of them eg. If I picked 2 particles in the first tomogram close the interface for the picking job then continue the job all the tomograms will  show done with 2 particles each. This would be a total of 80 particles. If I close the job and then continue again each tomogram will show that it now contains 80 particles each.

Attached is the error log I get.
