### ISSUE TITLE
accumulated dose is lost in the tilt series alignment

### ISSUE THREAD

**Issue by Vilax** [scipion-em/scipion-em-emantomo#55]
Running the emantomo - Reconstruction test

The first step is an import TS and the accumulated dose is properly set as the image shows

![imagen](https://user-images.githubusercontent.com/12271438/209349303-67d8156a-23e3-4a74-ab3a-7536b446b1c0.png)

However, when the tilt series alignment is carried out the accumulated dose is lost taking the final dose. See image

![imagen](https://user-images.githubusercontent.com/12271438/209349415-469c830f-52a9-42a3-bebe-dada61c382ca.png)

**Comment by JorMaister** [comment]
Hi, @Vilax,
Many thanks for reporting. We're discussing if the TS alignment and tomogram reconstruction should be included in the new plugin release. What do you think about it? Meanwhile, if you are using it, I'll fix it.
