### ISSUE TITLE
Missing_Dependencies hint suggestion

### ISSUE THREAD

**Issue by wlugmayr** [scipion-em/scipion-em-emantomo#62]
I tried to install this plugin and it failed and the hint:
 
- OpenGL::OpenGL or similar does not exists --> sudo apt-get install libsm-dev libxrender-dev build-essential libgl1-mesa-dev mesa-utils mesa-common-dev libglu1-mesa libglu1-mesa-dev

was misleading. I installed on CentOS7 with gcc 4.8.5 but emantomo requires gcc 5.x or higher.
When I loaded gcc11 before installing this plugin everything worked. 

Can you please add the compiler dependecy to the hints?

**Comment by azazellochg** [comment]
hints have been long removed now
