### ISSUE TITLE
PCA error

### ISSUE THREAD

**Issue by Vilax** [scipion-em/scipion-em-emantomo#77]
The PCA raises the next error 

see alter5 for more info
project: pickingvesicles

It seems related with the number of subtomos per tomogram. The index starts at 0 and there are 632 rows in the text file generated by eman, however it attemps to access to the row 633. This blind shot is my guess

![image](https://github.com/scipion-em/scipion-em-emantomo/assets/12271438/64fb3e39-f5c7-4a24-b4e6-59b59eb0fdd3)

![image](https://github.com/scipion-em/scipion-em-emantomo/assets/12271438/28b27cb3-c1f0-4a0f-9fa4-a9dc62fd2201)

![image](https://github.com/scipion-em/scipion-em-emantomo/assets/12271438/7d452195-3c1c-4b36-9663-5c1c6af1aba1)

**Comment by JorMaister** [comment]
Solved
